name: Deploy Cloud Functions
on:
  workflow_dispatch:
    inputs:
      project:
        description: "Firebase project"
        required: true
        type: choice
        options:
          - barbaard-dev
          - barbaard-prod
      functionList:
        description: "Function list: eg. functions:server,functions:onUserCreate..etc"
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - id: release
        run: |
          echo "version=$(cat apps/api/package.json | jq -r '.version')" >> $GITHUB_OUTPUT

      - run: |
          npm install -g firebase-tools

      - name: Deploy functions
        run: |
          firebase deploy -P ${{ inputs.project }} --only functions:${{ inputs.functionList }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Post to a Slack channel
        if: inputs.project == 'barbaard-dev'
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: "C05KWP6E7EU"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🚧 functions ${{ steps.release.outputs.version }} : *${{ inputs.functionList }}*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:* <${{ github.event.repository.html_url }}/tree/${{ github.ref_name }}|`${{ github.ref_name }}`>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:* <${{ github.event.repository.html_url }}/commit/${{ github.sha }}|`${{ github.sha }}`>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Author:* ${{ github.actor }}"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "⏳ - preivew channel 💡 - live channel 🚧 - STAGING 🚀 - PROD"
                    }
                  ]
                }
              ]
            }

      - name: Post to a Slack channel
        if: inputs.project == 'barbaard-prod'
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: "C05KWP6E7EU"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🚀 functions ${{ steps.release.outputs.version }} : *${{ inputs.functionList }}*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:* <${{ github.event.repository.html_url }}/tree/${{ github.ref_name }}|`${{ github.ref_name }}`>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Commit:* <${{ github.event.repository.html_url }}/commit/${{ github.sha }}|`${{ github.sha }}`>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Author:* ${{ github.actor }}"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "⏳ - preivew channel 💡 - live channel 🚧 - STAGING 🚀 - PROD"
                    }
                  ]
                }
              ]
            }
