name: Function Integration Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - "apps/api/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Build Packages
        run: |
          pnpm run build --filter=api

      - name: Test
        run: |
          pnpm run test:ci
