name: Sync main->staging

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0
      - name: Sync
        run: |
          git config user.name github-actions
          git config user.email github-actions@barbaard.com
          git merge origin/main --no-edit
          git push origin staging
